name: Run tests

on:
  push:
    branches: [ci_cd]

jobs:
  unit_test:
    name: Unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: python manage.py test
